### ISSUE TITLE
[Tech] TODO Lists

### ISSUE THREAD

**Issue by phodal** [phodal/growth2#2]
技术

- [ ] CI构建完成后，自动复制www目录下的内容到某个GitHub Page，做自动部署。
- [ ] Spike React Native 
- [x] 转换content的图片为jpg，或者其他更适合手机浏览器的格式
- [x] CI构建完成后，自动打包APP，并上传。
- [ ] 压缩所有的content的html文件到一起，插件如gulp-inline-ng2-template

**Comment by phodal** [comment]
http://stackoverflow.com/questions/26502970/merge-multiple-git-repositories-into-one-keeping-branches-history

**Comment by phodal** [comment]
Merge to Master http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories
